---
version: '3'
services:

  db:
    container_name: $DB_CONTAINER
    image: mariadb:latest
    restart: always
    volumes:
      - /srv/www/${VIRTUAL_HOST}/db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  wp:
    container_name: $WP_CONTAINER
    build: .
    depends_on:
      - db
      - cp
    restart: always
    volumes:
      - ./theme:/var/www/html/wp-content/themes/${WP_THEME}:rw
      - ./plugin:/var/www/html/wp-content/plugins/${WP_PLUGIN}:rw
      - /srv/www/${VIRTUAL_HOST}/wp_content:/var/www/html/wp-content:rw
    environment:
      WORDPRESS_DB_HOST: $DB_CONTAINER
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WP_TABLE_PREFIX
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      #LETSENCRYPT_TEST: 'true'

  cp:
    build: composer
    container_name: ${COMPOSER_CONTAINER}
    volumes:
      - /srv/www/${VIRTUAL_HOST}/wp_content:/app/wp-content
    command: composer install

  ftp:
    # optionally replace username/repo:tag with your name and image details
    image: stilliard/pure-ftpd:latest
    environment:
      PUBLICHOST: ${FTP_PUBLIC_HOST}
      FTP_USER_NAME: "bob"
      FTP_USER_PASS: "foobarqux"
      FTP_USER_HOME: "/var/www/html/wp-content/themes/${WP_THEME}"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    volumes:
    - ./theme:/var/www/html/wp-content/themes/${WP_THEME}:rw
    # - ./data/ftp:/etc/ssl/private
    ports:
    - target: 21
      published: 21
      protocol: tcp
      mode: host
    # Bind each passive ports to the host
    - target: 30000
      published: 30000
      protocol: tcp
      mode: host

  # phpmyadmin
  pma:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - '8080:80'
    environment:
      PMA_HOST: ${VIRTUAL_HOST}
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

networks:
  default:
    external:
      name: nginx_proxy

